# Generated by Django 4.2.2 on 2025-02-26 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('ay_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=25)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('current_ay', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Academic_year',
            },
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('data', models.JSONField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'BlockchainRecord',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='Educational_level',
            fields=[
                ('el_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Educational_level',
            },
        ),
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('lt_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=60)),
                ('days', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Leave_type',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.TextField()),
                ('user_type', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Salary_table',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_category', models.CharField(max_length=20)),
                ('basic_pay', models.IntegerField()),
                ('da', models.FloatField()),
                ('hra', models.FloatField()),
                ('ta', models.FloatField()),
                ('agp', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.designation')),
            ],
            options={
                'db_table': 'Salary_table',
            },
        ),
        migrations.CreateModel(
            name='School_finance',
            fields=[
                ('sf_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_category', models.CharField(max_length=20)),
                ('finance_type', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'School_finance',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.IntegerField()),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.educational_level')),
            ],
            options={
                'db_table': 'Standard',
            },
        ),
        migrations.CreateModel(
            name='Student_fee',
            fields=[
                ('sf_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_category', models.CharField(max_length=20)),
                ('fee_type', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.educational_level')),
            ],
            options={
                'db_table': 'Student_fee',
            },
        ),
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('image', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.login')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.standard')),
            ],
            options={
                'db_table': 'Student_register',
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_date', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.academic_year')),
                ('from_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='schoolapp.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_register')),
                ('to_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='schoolapp.standard')),
            ],
            options={
                'db_table': 'StudentPromotion',
            },
        ),
        migrations.CreateModel(
            name='Student_fee_transaction',
            fields=[
                ('sft_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('created_at', models.DateField()),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.academic_year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_register')),
                ('student_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.student_fee')),
            ],
            options={
                'db_table': 'Student_fee_transaction',
            },
        ),
        migrations.CreateModel(
            name='Staff_register',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('contact_number', models.BigIntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.designation')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.login')),
            ],
            options={
                'db_table': 'Staff_register',
            },
        ),
        migrations.CreateModel(
            name='Staff_leave',
            fields=[
                ('sl_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20, null=True)),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.leave_type')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.staff_register')),
            ],
            options={
                'db_table': 'Staff_leave',
            },
        ),
        migrations.CreateModel(
            name='School_finance_transaction',
            fields=[
                ('sft_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('total_amount', models.FloatField()),
                ('entry_date', models.DateField()),
                ('approval_status', models.CharField(max_length=20, null=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.academic_year')),
                ('school_finance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.school_finance')),
            ],
            options={
                'db_table': 'School_finance_transaction',
            },
        ),
        migrations.CreateModel(
            name='Salary_transaction',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus', models.FloatField(default=0, null=True)),
                ('deductions', models.FloatField(default=0, null=True)),
                ('da_amount', models.FloatField(default=0, null=True)),
                ('hra_amount', models.FloatField(default=0, null=True)),
                ('ta_amount', models.FloatField(default=0, null=True)),
                ('agp_amount', models.FloatField(default=0, null=True)),
                ('basic_pay', models.FloatField()),
                ('salary_date', models.DateField()),
                ('approval_status', models.CharField(max_length=20, null=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.academic_year')),
                ('salary_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.salary_table')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.staff_register')),
            ],
            options={
                'db_table': 'Salary_transaction',
            },
        ),
    ]
