# Generated by Django 4.2.2 on 2025-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee',
            name='term',
            field=models.CharField(choices=[('1', 'First Term (June-August)'), ('2', 'Second Term (September-November)'), ('3', 'Third Term (December-March)')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
