# Generated by Django 4.2.2 on 2025-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_student_fee_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee_transaction',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student_fee_transaction',
            name='late_payment_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_fee_transaction',
            name='late_payment_penalty',
            field=models.FloatField(default=0),
        ),
    ]
