# Generated by Django 4.2.2 on 2025-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_student_fee_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee_transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_fee_transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
