# Generated by Django 4.2.2 on 2025-03-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_student_fee_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_fee_transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='student_fee_transaction',
            name='reference_number',
        ),
    ]
