# Generated by Django 4.2.2 on 2025-03-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_remove_student_fee_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Limits',
            fields=[
                ('fl_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_type', models.CharField(max_length=150)),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.educational_level')),
            ],
            options={
                'db_table': 'Fee_Limits',
                'unique_together': {('educational_level', 'fee_type')},
            },
        ),
    ]
