# Generated by Django 4.2.2 on 2025-03-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_fee_limits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee_Limits',
        ),
    ]
