# Generated by Django 4.2.2 on 2025-03-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_attendancestatus_staffattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancestatus',
            old_name='as_id',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='attendancestatus',
            old_name='status',
            new_name='status_name',
        ),
        migrations.RenameField(
            model_name='staffattendance',
            old_name='created_at',
            new_name='marked_at',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='updated_at',
        ),
    ]
