# Generated by Django 4.2.2 on 2025-03-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_rename_as_id_attendancestatus_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='max_days_per_month',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.academic_year'),
        ),
        migrations.AlterField(
            model_name='leave_type',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('vacation', 'Vacation Leave')], max_length=60, unique=True),
        ),
    ]
