# Generated by Django 4.2.2 on 2025-03-14 08:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_remove_sick_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_type',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('vacation', 'Vacation Leave')], max_length=60, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_leave_type', message='Only Casual Leave and Vacation Leave are allowed', regex='^(casual|vacation)$')]),
        ),
        migrations.CreateModel(
            name='AttendanceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.academic_year')),
            ],
            options={
                'unique_together': {('date', 'academic_year')},
            },
        ),
    ]
