# Generated by Django 4.2.2 on 2025-03-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_alter_leave_type_leave_type_attendancelock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceLock',
        ),
    ]
