# Generated by Django 4.2.2 on 2025-03-17 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_delete_attendancelock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffattendance',
            old_name='marked_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'attendance_date', 'academic_year')},
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='status_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='marked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.login'),
            preserve_default=False,
        ),
    ]
